coin: 'XRP'
currency: 'ZAR'
profitPercentage: 0.25
trendSize: 2
downTrendMarginStart: 99.99 #99.80
downTrendMarginEnd: 98.65
upTrendMarginStart: 100.01
upTrendMarginEnd: 101
purchasePercent: 10
minTradeAmount: {'XRP': 1}
sellGroupMargin : 0.05
buyMargin: 0.05
cancelCount: 6
buyPriceMargin: 1000
