coin: 'XRP'
currency: 'ZAR'
profitMargin: 0.25
trendSize: 2
trendMargin: 99.90 #99.80
minTrendMargin: 99.60
purchaseTrendMargin: 96.50
purchasePercent: 5
minTradeAmount: {'XRP': 1}
sellRangeMargin : 0.10
psoProfit: 0.35 # Possible Sell Order
buyMargin: 0.03
cancelCount: 3