coin: 'XRP'
currency: 'ZAR'
profitPercentage: 0.25
trendSize: 2
downTrendMarginStart: 99.90 #99.80
downTrendMarginEnd: 99.60
upTrendMarginStart: 100.05
upTrendMarginEnd: 100.20
purchasePercent: 20
minTradeAmount: {'XRP': 1}
sellGroupMargin : 0.10
profitAmount: 0.01 # Possible Sell Order
buyMargin: 0.05
cancelCount: 3
