coin: 'XRP'
currency: 'ZAR'
profitPercentage: 0.25
trendSize: 6
downTrendMarginStart: 99.99 #99.80
downTrendMarginEnd: 98.50
upTrendMarginStart: 100.01
upTrendMarginEnd: 101
purchasePercent: 25
minTradeAmount: {'XRP': 1}
sellGroupMargin : 0.10
buyMargin: 0.007
cancelCount: 12
buyPriceMargin: 1000